/* Corre las suites de pruebas en Node: node tests/run-node.js */
require('../assets/js/design.js');
require('../assets/js/stats.js');
require('../assets/js/anova.js');
require('../assets/js/anova-nested.js');
require('../assets/js/attribute.js');
require('../assets/js/report.js');
require('../assets/js/mls.js');
require('../assets/js/interval.js');
require('./harness.js');
require('./tests.js');
require('./tests-nested.js');
require('./tests-design.js');
require('./tests-attribute.js');
require('./tests-report.js');
require('./tests-interval.js');
require('./tests-mls.js');
require('./tests-carga.js');
MSATestKit.report();
